image:
  name: gcr.io/kaniko-project/executor:debug
  entrypoint: [""] 

stages:
  - build
  - test

build:
  stage: build
  script:
    - echo "Hi Kevin, Running Kaniko"
    - echo "{\"auths\":{\"gitlab.cs.virginia.edu\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG 

test:
  stage: test
  script:
    - echo "Testing!"
    - exit 0
