stages:
  - build
  - test

build:
  stage: build
  script:
    - docker build -t dockerlocal . -m 16g --no-cache
    - docker tag dockerlocal gitlab.cs.virginia.edu:5099/physicalsemantics/peirce-docker-builder
    - docker push gitlab.cs.virginia.edu:5099/physicalsemantics/peirce-docker-builder
    - docker tag dockerlocal gitlab.cs.virginia.edu:5099/physicalsemantics/peirce
    - docker push gitlab.cs.virginia.edu:5099/physicalsemantics/peirce
    - echo 1 > output.txt

  artifacts:
    paths:
      - output.txt
