stages:
  - build
  - test

build:
  stage: build
  script:
    - docker build -t andrewe8/andrewpeircetest . -m 16g --no-cache
    - docker push andrewe8/andrewpeircetest
    - echo 1 > output.txt

  artifacts:
    paths:
      - output.txt
test:
  stage: test
  script:
    - echo "Testing!"
    - exit 0
